{"name": "显示满足条件的课程信息（输入存在的课程介绍，课程名称，课程学科，课程价格，适用人群）", "status": "failed", "statusDetails": {"message": "AssertionError: assert ('\\n'\\n '### Error updating database.  Cause: '\\n 'com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too '\\n \"long for column 'name' at row 1\\n\"\\n '### The error may exist in URL '\\n '[jar:file:/root/kdtx/huike-admin.jar!/BOOT-INF/lib/huike-clues-3.4.0.jar!/mapper/clues/TbCourseMapper.xml]\\n'\\n '### The error may involve '\\n 'com.huike.clues.mapper.TbCourseMapper.insertTbCourse-Inline\\n'\\n '### The error occurred while setting parameters\\n'\\n '### SQL: insert into tb_course          ( code,             '\\n 'name,             subject,             price,             '\\n 'applicable_person,             info,             create_time )           '\\n 'values ( ?,             ?,             ?,             ?,             '\\n '?,             ?,             ? )\\n'\\n '### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data '\\n \"truncation: Data too long for column 'name' at row 1\\n\"\\n \"; Data truncation: Data too long for column 'name' at row 1; nested \"\\n 'exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data '\\n \"truncation: Data too long for column 'name' at row 1\") == '操作失败'\n  - 操作失败\n  + \n  + ### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1\n  + ### The error may exist in URL [jar:file:/root/kdtx/huike-admin.jar!/BOOT-INF/lib/huike-clues-3.4.0.jar!/mapper/clues/TbCourseMapper.xml]\n  + ### The error may involve com.huike.clues.mapper.TbCourseMapper.insertTbCourse-Inline\n  + ### The error occurred while setting parameters\n  + ### SQL: insert into tb_course          ( code,             name,             subject,             price,             applicable_person,             info,             create_time )           values ( ?,             ?,             ?,             ?,             ?,             ?,             ? )\n  + ### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1\n  + ; Data truncation: Data too long for column 'name' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1", "trace": "self = <test_case.add_center.test_data_add.Test_add object at 0x000001D2C64CF280>\nlogin_fixture = 'eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbl91c2VyX2tleSI6ImRjN2UwNzg5LTQ1YTgtNGU2NC1hNDg1LTY3NGVjMDEzYWM0YSJ9.ZHfviBMgKrdkAc39AHoyAvuIxCPtJq9SnxO-q2cfpTcPEyL4BX4-OM8ZMroKEeFrJ-o3EnZlJnxx9kE_LavnBA'\nname = '测试开发提升课011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'\nsubject = 8, price = 999, applicablePerson = 3, info = ''\n\n    @allure.severity(severity_level=\"critical\")\n    @pytest.mark.parametrize(\"name,subject,price,applicablePerson,info\", [get_data()['add'][3]])\n    def test_add_04(self,login_fixture,name,subject,price,applicablePerson,info):\n        headers = {\n            \"Authorization\": login_fixture\n        }\n        json={\n            \"name\": name,\n            \"subject\": subject,\n            \"price\": price,\n            \"applicablePerson\":applicablePerson,\n            \"info\": info\n        }\n        ######动态自定义allure报告，title和story的信息写在yaml文件中\n        title = get_data()['text']['title']\n        story = get_data()['text']['story']\n        allure.dynamic.title(title)\n        allure.dynamic.story(story)\n        ##########################################\n        #r = api_utils.api_search(params=params,headers=headers)    ###关键字传参\n        r = response.post_add_query(headers=headers,json=json)\n        assert r.status_code == 200\n        result=r.json()\n>       assert result['msg']== \"操作失败\"\nE       assert ('\\n'\\n '### Error updating database.  Cause: '\\n 'com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too '\\n \"long for column 'name' at row 1\\n\"\\n '### The error may exist in URL '\\n '[jar:file:/root/kdtx/huike-admin.jar!/BOOT-INF/lib/huike-clues-3.4.0.jar!/mapper/clues/TbCourseMapper.xml]\\n'\\n '### The error may involve '\\n 'com.huike.clues.mapper.TbCourseMapper.insertTbCourse-Inline\\n'\\n '### The error occurred while setting parameters\\n'\\n '### SQL: insert into tb_course          ( code,             '\\n 'name,             subject,             price,             '\\n 'applicable_person,             info,             create_time )           '\\n 'values ( ?,             ?,             ?,             ?,             '\\n '?,             ?,             ? )\\n'\\n '### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data '\\n \"truncation: Data too long for column 'name' at row 1\\n\"\\n \"; Data truncation: Data too long for column 'name' at row 1; nested \"\\n 'exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data '\\n \"truncation: Data too long for column 'name' at row 1\") == '操作失败'\nE         - 操作失败\nE         + \nE         + ### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1\nE         + ### The error may exist in URL [jar:file:/root/kdtx/huike-admin.jar!/BOOT-INF/lib/huike-clues-3.4.0.jar!/mapper/clues/TbCourseMapper.xml]\nE         + ### The error may involve com.huike.clues.mapper.TbCourseMapper.insertTbCourse-Inline\nE         + ### The error occurred while setting parameters\nE         + ### SQL: insert into tb_course          ( code,             name,             subject,             price,             applicable_person,             info,             create_time )           values ( ?,             ?,             ?,             ?,             ?,             ?,             ? )\nE         + ### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1\nE         + ; Data truncation: Data too long for column 'name' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1\n\ntest_data_add.py:132: AssertionError"}, "attachments": [{"name": "log", "source": "8b5c51b9-87be-4e30-a7c0-7c6cec66ddf9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "name", "value": "'测试开发提升课011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'"}, {"name": "subject", "value": "8"}, {"name": "price", "value": "999"}, {"name": "applicablePerson", "value": "3"}, {"name": "info", "value": "''"}], "start": 1723811613674, "stop": 1723811613869, "uuid": "c5549533-f7db-49dd-ab0e-fe8eef45de36", "historyId": "45de0560876f61f28f42869485d3d393", "testCaseId": "3788f5e741f927a19e5b7a5c3c3de90e", "fullName": "test_case.add_center.test_data_add.Test_add#test_add_04", "labels": [{"name": "story", "value": "查询列表story"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "添加课程"}, {"name": "parentSuite", "value": "test_case.add_center"}, {"name": "suite", "value": "test_data_add"}, {"name": "subSuite", "value": "Test_add"}, {"name": "host", "value": "DESKTOP-SSRE6IE"}, {"name": "thread", "value": "13756-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.add_center.test_data_add"}]}