{"name": "test_get_search", "status": "broken", "statusDetails": {"message": "AttributeError: 'Api' object has no attribute 'user_login'", "trace": "@pytest.fixture(scope=\"session\")\n    def login_fixture():\n        data = get_data()['login1']\n        username = data['username']\n        password = data['password']\n        code=data['code']\n>       result= loginApi.login(username,password,code)\n\n..\\conftest.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <api.login_ok.LoginApi object at 0x0000023F23C7E280>, username = 'admin'\npassword = 'HM_2023_test', code = 2\n\n    def login(self,username, password,code):\n        \"\"\"\n        用户登录接口\n        :param username:\n        :param password:\n        :return:\n        \"\"\"\n        json_data = {\n            \"username\": username,\n            \"password\": password,\n            \"code\":code,\n            \"uuid\":LoginApi.uuid\n    \n        }\n    \n>       return api_util.user_login(json=json_data)\nE       AttributeError: 'Api' object has no attribute 'user_login'\n\n..\\..\\api\\login_ok.py:47: AttributeError"}, "start": 1723724117799, "stop": 1723724117799, "uuid": "eda8cd2f-de7e-41e6-9413-b3d4e60f83e0", "historyId": "8f194988b3c67b4451ecf2193e46f567", "testCaseId": "8f194988b3c67b4451ecf2193e46f567", "fullName": "test_case.search_center.test_data_list.Test_search#test_get_search", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "查询课程列表模块"}, {"name": "epic", "value": "客达天下epic"}, {"name": "parentSuite", "value": "test_case.search_center"}, {"name": "suite", "value": "test_data_list"}, {"name": "subSuite", "value": "Test_search"}, {"name": "host", "value": "DESKTOP-SSRE6IE"}, {"name": "thread", "value": "20164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.search_center.test_data_list"}]}